= Basic Pickles or Fermented Cucumbers Recipe

:slug: basic-pickles-or-fermented-cucumbers-recipe
:date: 2019-08-10 23:01:23
:modified: 2021-06-15 21:25:39-07:00
:tags: food, fermentation
:meta_description: lotem ipsim dolor sit amet

Here's my fermented cucumbers recipe. This is adapted from https://www.amazon.co.uk/Wild-Fermentation-Flavor-Nutrition-Live-Culture-ebook/dp/B01KYI04CG[the Wild Fermentation book] - which is very good.

== Equipment

* Clean wide mouth mason jars - or any vaguely similar container
* A small ziplock bag 50% full of tap water, as a weight/seal for the container
* A Cabbage leaf

== Ingredients

* Fresh un-waxed small cucumbers/gherkins - however many you want to make

[discrete]
==== Brine (per litre)
* 1 litre water
* 50g (3 level tablespoons) salt (just salt, no added ingredients)

[discrete]
==== Per jar
* 2 sprigs fresh dill
* 1 tsp black peppercorns (you can use ground pepper if you don't have whole)
* 1 tsp mustard or coriander seeds
* A bay leaf

== Process

. Soak cucumbers in cold water for a bit, then rinse/rub, taking care to not bruise them, and making sure their blossoms are removed. Top & tail them.
. While the cucumbers are soaking, dissolve sea salt in water to create brine solution. Stir until salt is thoroughly dissolved. ~80% of the space in your jars will be filled with cucumbers, so don't make _too much_ brine.
. Put dill, peppercorns & seeds into jars
. Pack cucumbers into the jars, length-ways, or cut sideways. Leave several inches of headspace at the top of the jar - enough to fit the ziplock bag weight.
. Pour brine over the cucumbers, put cabbage leaf over the top to stop anything floating to the surface. Again, leave several inches of headspace at the top of the jar - enough to fit the ziplock bag weight
. Put the water filled ziplock bag into the top of the jar, as a seal & weight, to keep everything underneath the brine.
. Put the jars somewhere with a steady temperature, away from direct sunlight, roughly room temperature. Warmer makes the go faster, too warm makes them into mush; room temp is fine.
. After a few days the water should go cloudy - this means it's working and they've started to ferment.
. Check the jar every few days. Skim any mould/yeast from the surface of the water, but don't worry if you can't get it all. If there's mold, be sure to rinse the bag & put back. Taste the pickles after about a week.
. Feel free to remove and eat the pickles as they continue to ferment, until you decide how sour you like them - longer fermentation will increase sourness. Continue to check occasionally.
. Eventually, after one to four weeks (depending on the temperature), the pickles will be fully sour. Continue to enjoy them, moving them to the fridge to slow down fermentation. I usually leave mine for roughly 2 weeks.

== Mixed Vegetable Ferments

The process described above is not limited to cucumber pickles. Pretty much any vegetable you have in abundance, except for ripe tomatoes which get soft and lose their form, can be fermented in this way. Basically, anything crunchy at the start, will ferment well this way.

Good luck and let me know how you get on!
