= Fermented Bánh Mì(ish) Recipe

:slug: fermented-banh-mi-ish-recipe
:date: 2020-04-28 14:22:17-07:00
:modified: 2021-06-15 14:37:15T-07:00
:tags: food, fermentation

This is a rather loose adaptation of a https://cultured.kiwi/recipes/cultured-veggies/banh-mi-pickles/[traditional Vietnamese recipe], which you can google for lots of variations.

If you can't get daikon radish, you just whatever radish you can get.

== Basic Brine
* 45g salt per litre of water
* Mix to dissolve

Important to measure carefully. This is the brine I use for everything, unless I find a recipe that has a good reason for using something different.

== Ingredients

* 1/2 Daikon Radish (650g)
* 4 carrots (650g)
* 85g ginger
* 1 jalapeno/green/red chili (to taste)
* Basic Brine to cover

== Instructions

Makes about 1 large jar.

. Lightly wash/rinse all veg, but leave skin on everything, including Ginger.
. Grated or spiralize about equal amounts of daikon radish & carrots.
. Grate Ginger with skin on, cut chili in half. If spiralized, roughly chop with scissors, so strands are not too long.
. Mix carrot, radish & ginger; add a few tsp of salt.
. Put a handful of mixture in bottom of jar. Push chili halves down the sides, so that the mixture holds them up.
. Fill jar with mixture, packing it down to remove air pockets.

Leave _large_ amount of headspace at top of jar - at least 3"/8 cm. Add weight, top up with brine to top of jar. You will get evaporation and the ferment time is long, so a big brine header is needed.

I usually leave for ~8-10 weeks, depending on temperature, etc...
Mine was very active to start, then settled down. I like the flavours to mellow and combine over the long ferment time - but I would suggest that the first time you make them, you open them and taste them every week or so and see what you like best.
If you forget about them for a few weeks (or months) ... they'll be fine!
After my ferment, the Radish is translucent it's all soft/al dente, and the flavours have combined & mellowed.