= The Keys To Successful Fermenting

:slug: the-keys-to-successful-fermenting
:date: 2021-06-15 14:31:19-07:00
:tags: fermentation,food
:meta_description: 

* Keep everything underneath the brine - make sure nothing rises to, or floats on, the surface. Anything on the surface will go mouldy after a while.
* Leave headspace at the top of the jar - i.e. a layer of clear brine, above the ferment & weights. For short ferments up to a month, 1"/3 cm. For longer ferments, double it.
* You may get kahm yeast on the surface of the water. It looks like a thin white mostly flat layer/patches on the surface. It's harmless, but if you leave it too long it'll make things taste off - skim it off with a spoon or kitchen paper. Anything furry/hairy is mould, if you catch it early, skim it off and carry on. If it looks black/pink/angry or has taken over, remove it, try a pickle and see what you think, but maybe compost the lot to be on the safe side.
* Either don't fully seal the jar, or unscrew the lid every day or two - the ferment will produce some CO₂, possibly causing jars/lids to burst.
* If you find yourself doing a lot of fermenting in mason jars, these are excellent and reduce mould and increase ease & reliability quite a bit: https://www.amazon.co.uk/Easy-Fermenter-Wide-Mouth-Lid/dp/B01DJVVORE/[Easy Fermenter Wide Mouth Lid Kit]

