:title: Super Fast Reader Mode for the Entire Web, with Dillo Plus
:slug: super-fast-reader-mode-for-the-entire-web-with-dillo-plus
:created: 2024-01-04 00:32:59+00:00
:date: 2024-01-04 00:32:59+00:00
:modified: 2024-01-15 11:15:21+00:00
:tags: web,dillo,css,linux
:category: tech
:meta_description: Want "Reader Mode" for (almost) the entire web - and have every page load almost instanly? Here's how.

[.lead]
Want "Reader Mode" for almost the entire web - and have every page load nearly instantly? Here's how.

There are three main constellations of Web Browsers - ones based on Google's Blink https://en.wikipedia.org/wiki/Comparison_of_browser_engines[rendering engine] (used in Google Chrome, MS Edge, Vivaldi, Brave and others), ones based on WebKit (used in Safari on MacOS & iOS 7 iPadOS) - and on Mozilla's Geko engine (used by https://www.mozilla.org/firefox/[Firefox] & Thunderbird).

There are also a few other, _"non-mainstream browsers"_, that have their _own_ engines. Cosmic wanderers, not part of the main constellations, that chart their own course, building everything themselves: https://en.wikipedia.org/wiki/Flow_(web_browser)[Flow], https://servo.org/[Servo], https://ladybird.dev/[LadyBird], https://www.netsurf-browser.org/[NetSurf] - and https://github.com/crossbowerbt/dillo-plus[Dillo-Plus].

== Dillo Plus has a Tiny Superpower

Actually, the Dillo-Plus browser has quite a few https://github.com/crossbowerbt/dillo-plus#browser-features[tiny superpowers] - but the one I'm interested in is its ability to _ignore all the CSS styles from the website and load your CSS instead_:

.Before and After - Firefox on the left, Dillo Plus (and my stylesheet) on the right.
image::{static}/images/posts/{slug}/before-and-after-3.avif["Screenshots of three web pages, each with two browser windows side by side - one of Firefox showing the normal appearance and one with Dillo Plus and my stylesheet, showing the Reader Mode version."]

Most browsers except Chrome support "User CSS" in some form, although they mostly don't advertise this and make it difficult to set up. But, as far as I know, they all load the website's CSS styles _first_, then apply your user styles _on top_.

This is fine -- and is how the "Cascading" in Cascading Style Sheets is _supposed_ to work, after all. It allows you to override things you don't like, and this works OK-ish for little things -- but you're always _fighting_ with the styles from the website.

.Use the "Tools" menu to switch off all other CSS (uncheck the first two options) - and switch on your Reader/User Mode CSS.
image::{static}/images/posts/{slug}/dillo-tools-menu.avif["Screenshot of the Dillo Plus tools menu, showing the options: 'Use remote CSS' (unchecked), 'Use embedded CSS' (unchecked) - and 'Use reader mode CSS', which is checked."]

If you want to override _lots of things_ (or everything), you tend to end up with large, unwieldy CSS that overrides tons of things, as well as lots of little CSS overrides for individual websites - and it ends up full of `!important` qualifiers to make your styles override previously applied ones.

Dillo Plus allows you to avoid all that messing around and just _**switch off all other CSS except yours**_. This sounds pretty basic, but I don't know of any other browser that supports this - and the difference it makes is _massive_.

== Your Web, Your Way

Once you do this, _all_ the websites you visit will suddenly look the way _you_ want them to. Want everything in Dark mode? Want everything to use the same font? Want all the fonts to be larger, everywhere? No problem, done. Whatever you want, everywhere, all at once.

_**Once you browse around this way for a while, the web starts to feel a little bit like one giant website, that's so fast it's just... part of your computer.**_

== Bring that Smolnet/Gemini Simplicity (back) to the Web

If you've used https://en.wikipedia.org/wiki/Gemini_(protocol)[Gemini], or https://en.wikipedia.org/wiki/Gopher_(protocol)[Gopher], or the early Web, you will know what I mean here, but it's a feeling of simplicity and coherence, as well as a more homespun feel, rather than flashy commercial design in your face all the time. It's... nice, if you like that sort of thing.

As a bonus, Dillo-Plus _not only_ supports Gemini & Gopher, but _also_ applies all this CSS magic to Gemini & Gopher footnote:[Gemini pages look like web pages, Gopher pages look like Gopher pages - i.e. preformatted text] pages, making the whole web smol!

== Get Dillo Plus

You can get https://github.com/crossbowerbt/dillo-plus[Dillo-Plus here], but you are going to have to build it from source yourself. Yes, I _know_. Doing this on Linux is pretty painless, only takes a minute and just worked for me. I have not tried any other platforms, although it supports lots. This is how I did it on Ubuntu 22.04:

First check out the source code:

[source,console]
----
$ git clone git@github.com:crossbowerbt/dillo-plus.git
$ cd dillo-plus
----

Check if you have the required build dependencies installed:

[source,console]
----
$ fltk-config --version
// I didn't, so I installed it:
$ sudo apt install libfltk1.3-dev
----

Build the browser:

[source,console]
----
$ make clean && make
----

Install it - this will overwrite any existing Dillo you might have installed:

[source,console]
----
$ sudo make install
----

== The Reader Mode User Stylesheet

Dillo-Plus does ship with a built-in Reader Mode Stylesheet, but I made one that I like much better. Bear in mind that Dillo doesn't support fancy new CSS things like variables, or units like `rem`, so I've avoided those:

[.scrollable]
[source,css]
----
include::/home/duncan/Projects/dillo-reader-mode-css/simple-readability.css[]

----

That's it, currently - 84 lines of CSS, including blank lines & comments, to restyle the entire web!

I've put this https://github.com/dflock/dillo-reader-mode-css[up on GitHub here] if you want to grab it that way, contribute updates or add new ones!

=== Make Dillo Plus Use Your Stylesheet

Dillo Plus puts its reader mode stylesheet here: `/usr/local/etc/dillo/style_reader_mode.css`, which is owned by `root`. So you will need to either edit this as `root`, or to make things easier, replace the bundled user stylesheet with symlink to your one, so you can edit it without being `root`:

[source,console]
----
$ sudo rm /usr/local/etc/dillo/style_reader_mode.css
$ sudo ln -s ~/dev/dillo-reader-mode-css/simple-dark.css /usr/local/etc/dillo/style_reader_mode.css
----

[NOTE]
====
Once you've done this, dillo will load your stylesheet on every page refresh, so you can just edit, save and refresh to see your changes!
====

== Upsides & Downsides of Browsing like it's 1999

So, this isn't all gravy - there _are_ some downsides to browsing like it's 1999:

=== Upsides

* No JavaScript, which basically means no ads or malware either.
* Dillo is fast anyway, but no JavaScript _really_ helps with this.
* Like, really fast.
* Your web, your way. Dark Mode? Done. Larger fonts? Done. Rainbow Background? Done. Whatever you want, everywhere, all at once.
* Bring that smolnet/Gemini simplicity (back) to the web.

=== Downsides

.The New York Times - Firefox on the left, Dillo Plus on the right. You can't read the article either way, but still...
image::{static}/images/posts/{slug}/new-york-times.avif["Screenshot of a New York Times article, Firefox on the left, Dillo Plus on the right. In the Firefox window, the article is obscured by Cookie popups and Paywalls. The Dillo Plus one is blank except for 'Please enable JS and disable any ad blocker'. "]

* No JavaScript, so websites that relay on JavaScript just don't work.
** Medium Articles load images via JavaScript with (apparently) no fallback, for example, so no images in Medium.
* Currently no SVG or Webp, AVIF etc... image support.
* You kind of get a taste of the "Screen Reader" experience of the Web - this is mostly that people building the websites aren't given time to build them with your browser in mind, nor testing in your setup, so things break/suck/work ok, depending.
* Commercial websites tend to have a _lot_ of navigation crap at the top - loads of nested lists of links - usually turned into dropdown menu's with CSS & JS. This will all get spat out at the top of the page. Some sites have a "Skip to Content" link at the top, which is very useful, but many don't.
* You have to build the browser from source code yourself. If you're on Linux, don't worry, it builds in a few seconds and just works.

== Could Firefox Support This, Please?

It would be really nice to have the option to do this in Firefox. That way you'd get all the support for modern CSS & image formats, as well as the ability to switch off all CSS except your own. These browsers _can_ already switch off JavaScript, although the option is rather buried in their settings, but not CSS.

---
=== References

. https://news.ycombinator.com/item?id=38995577[Discuss on Hacker News]

=== Footnotes