:title: If you could go say, 200 years in the future, but only stay for 24 hours, what would you do?
:slug: if-you-could-go-say-200-years-in-the-future-but-only-stay-for-24-hours-what-would-you-do
:date: 2012-11-28 01:56:06-08:00
:tags: reddit,writing
:category: tech
:meta_description:
:status: draft

https://www.reddit.com/r/FutureWhatIf/comments/13y3b3/if_you_could_go_say_200_years_in_the_future_but/

  Lets say that scientists have invented a time machine, but it is prohibitively expensive to make another one. The machine can take you to the future, but only for 24 hours and it can only be used once. What would be the best use of those 24 hours? Try to bring back technology? Try to find books to bring back? Talk to people?

Stare at the ashes of civilization and weep? Immediately get vivisected and uploaded by post singularity AIs? There is a flash of light and then something utterly incomprehensible happens?

Just think about all that's happened in the last 100 years. The Wright brothers managed to get a rickety wooden 'plane' off the ground for ~25 seconds ~100 years ago. This is the weather at Saturn's North Pole, yesterday: http://www.slate.com/blogs/bad_astronomy/2012/11/28/clouds_at_saturn_s_north_pole_form_huge_circular_and_hexagonal_storms.html

What are the chances of you going 200 years into the future and having the slightest clue what's going on? The pace of change is still accelerating - even if there's no singularity/discontinuity, the sheer amount of accumulated difference is going to make it like an encounter with an alien species.

---
=== Footnotes & References

