= Using AsciiDoc & Asciidoctor for blogging

:slug: using-asciidoc-and-asciidoctor-for-blogging
:date: 2021-01-12 11:31:39
:modified: 2021-05-12 23:11:45
:tags: asciidoc, blog, writing
:category: tech
:meta_description: Using AsciiDoc & Asciidoctor for blogging

:fn-asciidoctor-j: pass:q[footnote:fn-asciidoctor-j[Asciidoctor can also be run on the JVM - Asciidoctor-j (Java) or in a Browser/Nodejs - Asciidoctor-js (JavaScript). These are both just the Ruby version running in different places - either using JRuby to run on the JVM, or using the Opal Ruby to JavaScript source-to-source compiler to run the Ruby code on a JavaScript VM. The Opal runtime + the AsciiDoc source weighs in at about 1.2Mb of JS. These are both a bit fat and slow and don't really actually solve any of the AsciiDoc ecosystem's problems.]]

.Asciidoc.
image::{static}/images/posts/using-asciidoc-and-asciidoctor-for-blogging/asciidoctor-logo-blueprint-cropped-compressed.svg["Asciidoc", 500]


I have been using restructuredText for writing on this blog, because it has lots of built-in features that markdown doesn't.

However, restructuredText's _actual syntax_ is a bit... fiddly - particularly its non-atx headings, too many things relying on lining up white space, etc... If I don't use it for a bit, I have to look up or copy & paste all the advanced syntax.

I'd prefer to use AsciiDoc, as it has all the extra features, and if you use Asciidoctor, https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/[all the simple stuff is the same as markdown] - which isn't (currently) standard AsciiDoc, but is a nice simplification.

The subset of features from restructuredText (or Asciidoc) that Markdown doesn't have -- and that I'm _actually using_ on this blog, specifically, are:

* Figure/Images with captions
* Admonitions
* Front-matter/Metadata
* Footnotes

== Worse is better?

Markdown has _lots_ of problems. https://commonmark.org/[Until CommonMark] it was lazily, pointlessly, stubbornly non-standard - and had exploded into many fragmented semi-compatible dialects - and it has very few structural or semantic features. However, https://en.wikipedia.org/wiki/Worse_is_better[worse is better]. Markdown's simplicity makes it pretty simple to implement, to the extent that there are native implementations of Markdown in probably every language: https://bitbucket.org/yiyus/md2html.awk[AWK], https://github.com/chadbraunduin/markdown.bash[Bash], https://github.com/commonmark/cmark[C] ... to https://github.com/kivikakk/koino[Zig]. There are https://github.com/markdown/markdown.github.com/wiki/Implementations[hundreds] of more-or-less complete https://github.com/search?q=markdown+implementation[markdown implementations] to choose from, to fit any project; here are https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations[fifty high quality maintained ones, that support CommonMark, sorted by language], for example.

AsciiDoc is _much_ better than Markdown, but these extra features for the _writer_ come with extra complexity for the person _implementing_ the tools. Probably as a consequence, the AsciiDoc ecosystem and tooling is very anemic and leaves _a lot_ to be desired.

The _only_ complete and well maintained AsciiDoc processor is https://asciidoctor.org/[Asciidoctor] - which is written in Ruby. That's it - there are no other options as of early 2021{fn-asciidoctor-j}. I don't have anything against Ruby, particularly, but I don't know it or use it for anything, so it's not familiar. It _also_ has all the same well know problems as Python with packaging/running projects & managing dependencies. Instead of pip/setuptools/virtualenv, etc... it's gem/rbvenv/rake/bundler/rvm, etc... hundreds of global gem files, the whole giant mess. I get the impression that the Ruby version of this mess is... less of a problem somehow than the python one, but it's still a mess.

So, the AsciiDoc story is obviously much more limited than the markdown story. If you want native markdown support, you got it, no matter what you're doing. If you want native AsciiDoc support, you can only have it if your project is in Ruby (or Java & JavaScript with some caveats {fn-asciidoctor-j}). Other than that, you have to shell out and run a Ruby process - and have all the required Ruby dependencies installed.

This turns your document processing into a slower-than-it-could-be, annoying to setup and maintain, external black box. Don't take this the wrong way - the contents of that black box are _fantastic_ and good people have worked hard on it, but there are only a few of those people and pitting them against the markdown community - which is much larger - isn't really fair.

== What are the consequences of this for blogging?

=== Editing experience isn't as good

Most modern editors support AsciiDoc syntax highlighting and sometimes preview, via plugins. But, as expected, these aren't as well-developed, numerous or as fully featured as the Markdown equivalents. If you're using the Asciidoctor markdown-a-like syntax for the simple stuff, then you can just tell the editor it's Markdown, and use the more fully featured markdown support.

=== Not much native support

If you're using a Ruby blog engine, it _might_ have https://gist.github.com/briandominick/e5754cc8438dd9503d936ef65fffbb2d[native AsciiDoc support], or your blog engine might have a plugin that supports it. Don't expect every blog engine to support it, though. Some blog engines have an escape hatch that let you use https://pandoc.org/index.html[Pandoc] to process your content - and while Pandoc _does_ have AsciiDoc support, it's neither complete nor flawless.

=== Does native support matter?

Does the fact that the document processing is shelled out to a black box actually affect using AsciiDoc for blogging? Well, it makes publishing a bit slower to _a lot_ slower, depending on the size of your site. But in most blog/publishing systems you have a template the defines the structure of the page with some kind of placeholder that says `{{content-goes-here}}`. It doesn't really matter _how_ the content is generated, as long as it is - and as long as the HTML that's produced is reasonable...

=== Asciidoctor's built-in HTML output could be better

So, when `asciidoctor` processes your `.adoc` file you can tell it what converter (or "back-end") you want to use - i.e. what kind of output you want. https://docs.asciidoctor.org/asciidoctor/latest/converters/[These are the built-in options]. This is what they say about the default HTML converter:

"The HTML 5 converter (`html` or `html5`) generates HTML 5 styled with CSS3. This is the converter Asciidoctor uses by default."
-- https://docs.asciidoctor.org/asciidoctor/latest/converters/#built-in-converters[Asciidoctor Doc: Built-in converters]

This is _technically_ true, however, while the HTML it produces is _technically_ HTML5, it's also `<div>` soup. For example, this document processor for processing documents doesn't output paragraph tags (`<p>...</p>`) - it outputs this instead: `<div class="paragraph"><p>...</p></div>` - and it does something like that for basically everything. To be fair, https://github.com/asciidoctor/asciidoctor/issues/242[they are aware of this].

So, I'm not going to use that, I'll just use some community written back-end/converter that's better... oh... yeah. Well, luckily, in this case there actually _is_ one: https://github.com/jirutka/asciidoctor-html5s[html5s] - which does a _much_ better job.

== AsciiDoc Rough Edges

I've written this article from scratch and converted a few restructuredText articles to AsciiDoc, and it's been fairly painless, but I _have_ come across a few rough edges and problems with AsciiDoc.

=== Footnotes

AsciiDoc has https://docs.asciidoctor.org/asciidoc/latest/macros/footnote/[built-in support for footnotes], but there are some rough edges:

- https://github.com/asciidoctor/asciidoctor/issues/3690#issuecomment-778956139[Footnotes that have no ID get duplicated] So, this means that if you https://docs.asciidoctor.org/asciidoc/latest/macros/footnote/#externalizing-a-footnote[Externalize a footnote], then refer to it more than once, it'll get duplicated in the list of footnotes, unless you give it an ID. So, give footnotes IDs.
- https://github.com/asciidoctor/asciidoctor-pdf/issues/1397#issuecomment-780322751[Text formatting not being applied to footnotes] This means that text formatting, like *bold* and `monospace` don't get processed in footnotes, they'll come out literally, like \*bold* or \`monospace`. To fix this you need to use an "inline passthrough" which has slightly different syntax.

The combination of these two issues means that if you want text formatting in externalized footnotes, you have to give the footnote an ID and wrap the footnote definition in an inline pass-through. This is more complex & convoluted than it needs to be - footnotes should just work. Anyway, it looks like this:

[source,asciidoc]
----
:fn-disclaimer: pass:q[footnote:disclaimer[Opinions are *my own*.]]

A bold statement!{fn-disclaimer}

Another bold statement!{fn-disclaimer}
----

They are aware of this - here's a proposal for https://github.com/asciidoctor/asciidoctor/issues/559[an improved footnote syntax].

=== Blockquotes

I took me ages poking around on github before I found out how to set the link text in the citation for a quoted block. This is the basic syntax:

[source,asciidoc]
----
[quote, attribution, citation title and information]
Quote or excerpt text
----

You can put a URL in there, and it works, but giving the URL a title doesn't seem to work. So this works:

[source,asciidoc]
----
[quote, https://en.wikipedia.org/wiki/Main_Page]
Quote or excerpt text
----

but this doesn't:

[source,asciidoc]
----
[quote, https://en.wikipedia.org/wiki/Main_Page[Wikipedia]]
Quote or excerpt text
----

However, using the https://docs.asciidoctor.org/asciidoc/latest/blocks/blockquotes/#quoted-paragraph[Quoted paragraph] syntax works:

[source,asciidoc]
----
"Quote or excerpt text"
-- https://en.wikipedia.org/wiki/Main_Page[Wikipedia]
----

https://github.com/asciidoctor/asciidoctor/issues/1254[Apparently, the correct way to do this with quoted blocks], is to "use single quotes around the attribute value, that gives Asciidoctor the hint to apply normal substitutions (just like paragraph text)". Not sure what that means at this point, but to docs on https://docs.asciidoctor.org/asciidoc/latest/subs/substitutions/[subtitutions are here]. This is what it looks like in this case:

[source,asciidoc]
----
[quote, 'https://en.wikipedia.org/wiki/Main_Page[Wikipedia]']
Quote or excerpt text
----

== Using AsciiDoc with Pelican

I'm currently using https://blog.getpelican.com/[Pelican] for this blog and writing this post in AsciiDoc. This is what you need to do to get that working.

First https://asciidoctor.org/#gem-install[install the Ruby dependencies & Asciidoctor itself]. Unlike me, you should listen to them and use RVM for this. Once you have that installed, you need to https://github.com/jirutka/asciidoctor-html5s#installation[install html5s and its dependencies]. Next, you need to add the https://github.com/getpelican/pelican-plugins/tree/master/asciidoc_reader[asciidoc_reader Pelican Plugin] and add it to your `pelicanconf.py`

[source,python]
----
PLUGINS = [
    'asciidoc_reader',
]
----

You should then set the Asciidoctor command line options. These will configure it to use the `html5s` backend and https://github.com/rouge-ruby/rouge[rouge for source code syntax highlighting]:

[source,python]
----
ASCIIDOC_OPTIONS = [
    '-a source-highlighter=rouge',
    '-a rouge-style=monokai',
    '-r asciidoctor-html5s',
    '-b html5s'
]
----

Rouge is compatible with pygments - which I was using previously and my theme is set up to expect, so this was a drop in replacement - which is very convenient.

If you have existing restructuredText documents that you want to convert to AsciiDoc, the best way I've found to do this so far, uses https://pandoc.org/[Pandoc]. This is the basic command:

[source,shell]
----
pandoc --wrap=preserve -f rst -t asciidoctor "source.rst" > "dest.adoc"
----

This isn't perfect and messes up metadata, pelican `{static}` links and figures with captions, so you probably want some pre- & post-processing to fix that. I wrote a little script to do that:

[source,shell]
----
# 
# Pre-process
# 
cat "$src_path" | \
# Remove :alt: tags from figures & images, otherwise they get lost
sed -r 's/:alt: /\n/g' | \
# Tabs to spaces
sed -r 's/\t/  /g' | \
# 
# Convert rst to asciidoc using pandoc
# 
pandoc --wrap=preserve --from rst --to asciidoctor | \
# 
# Post-process
# 
# Fix metadata syntax, from date:: to :date:
sed -r 'N; s/^(.*)::\n /:\1:/g; P; D' | \
# Remove extra breaks created from figure caption conversion
sed -r 'N; s/____\n//g; P; D' | \
# Fix alt text for images/figures
perl -p0e 's/\[image\]\n\n(.*?)\n/[$1]\n/g' | \
# Make the line below the image into its caption
perl -p0e 's/image::(.*?)]\n\n(.*?)\n/\.$2\nimage::$1]\n/g' | \
# Fix Pelican {static} links
sed -e 's/%7B/{/g' -e 's/%7D/}/g' \
> "$src_folder/$src_name".adoc
----

The full version of this is https://github.com/dflock/duncanlock.net/blob/resurrection-and-asciidoc/rst2adoc.sh[available here].


== Future of AsciiDoc & Asciidoctor

There are a few promising projects that will help improve the AsciiDoc ecosystem.

=== The AsciiDoc Spec

The first and biggest one is that AsciiDoc is https://asciidoctor.org/news/2019/01/07/asciidoc-spec-proposal/[finally getting a proper spec], under the umbrella of the Eclipse Foundation. This is something that Markdown never had until CommonMark - and that AsciiDoc has lacked up to now. What this means is:

[quote, 'https://asciidoctor.org/news/2019/01/07/asciidoc-spec-proposal/[AsciiDoc Spec Proposal]']
____
The specification for the AsciiDoc language will include an open source specification document, which defines required and optional API definitions, semantic behaviors, data formats, and protocols, as well as an open source Technology Compatibility Kit (TCK) that developers can use to develop and test compatible implementations. ... A compatible implementation, as defined by the EFSP, must fully implement all non-optional elements of a specification version, must fulfill all the requirements of the corresponding TCK, and must not alter the specified API.

For users and developers alike, the AsciiDoc specification will mean a clear, working definition of what AsciiDoc is and how it should be interpreted. Developers will be able to build implementations, tools, and services around AsciiDoc without risk of diluting its meaning or splintering it. In turn, users will have more options, greater document portability, and the assurance that compatible implementations and tools will handle their AsciiDoc documents according to a versioned specification.
____

So, this should help prevent the fragmentation that plagues the Markdown ecosystem, as well a making it easier for people to develop AsciiDoc parsers & tools. Still nowhere near as easy as implementing a Markdown one, though - AsciiDoc is just more complex.

It'll be interesting to see what the optional elements end up being and if the required subset is sufficiently simple to make writing parsers & tools any easier.

=== libasciidoc

https://github.com/bytesparadise/libasciidoc[Liasciidoc is a Golang library for processing Asciidoc files]. This uses a https://en.wikipedia.org/wiki/Parsing_expression_grammar[PEG parser] with a formal grammar for AsciiDoc. It already supports a useful subset of AsciiDoc and is being actively worked on by a few people, I think with the intention to use it with https://gohugo.io/[Hugo], which will make a nice combination, when it's done.

Like most software written in Go, it's statically linked, which means no dependencies at all - you just need to put the `libacsiidoc` binary somewhere and run it. This is _really nice_ compared to setting up and maintaining the Ruby dependencies required for Asciidoctor, or the JS & Java ones for AsciiDocotor-J/Java, for example.

== Footnotes & References: