Here's the fermented cucumbers recipe. This is adapted from https://www.amazon.co.uk/Wild-Fermentation-Flavor-Nutrition-Live-Culture-ebook/dp/B01KYI04CG[the Wild Fermentation book] - which is very good.

== SPECIAL EQUIPMENT:

* Clean wide mouth mason jars - or any vaguely similar container
* A small ziplock bag 50% full of tap water, as a weight/seal for the container
* A Cabbage leaf

== INGREDIENTS:

* Fresh un-waxed small cucumbers/gherkins - however many you want to make

[discrete]
==== Brine (per litre):

* 1 litre water
* 50g (3 level tablespoons) salt (just salt, no added ingredients)

[discrete]
==== Per jar:
* 2 sprigs fresh dill
* 1 tsp black peppercorns (you can use ground pepper if you don't have whole)
* 1 tsp mustard or coriander seeds
* A bay leaf

== PROCESS:

. Soak cucumbers in cold water for a bit, then rinse/rub, taking care to not bruise them, and making sure their blossoms are removed. Top & tail them.
. While the cucumbers are soaking, dissolve sea salt in water to create brine solution. Stir until salt is thoroughly dissolved. ~80% of the space in your jars will be filled with cucumbers, so don't make _too much_ brine.
. Put dill, peppercorns & seeds into jars
. Pack cucumbers into the jars, length-ways, or cut sideways. Leave several inches of head space at the top of the jar - enough to fit the ziplock bag weight.
. Pour brine over the cucumbers, put cabbage leaf over the top to stop anything floating to the surface. Again, leave several inches of head space at the top of the jar - enough to fit the ziplock bag weight
. Put the water filled ziplock bag into the top of the jar, as a seal & weight, to keep everything underneath the brine.
. Put the jars somewhere with a steady temperature, away from direct sunlight, roughly room temperature. Warmer makes the go faster, too warm makes them into mush; room temp is fine.
. After a few days the water should go cloudy - this means it's working and they've started to ferment.
. Check the jar every few days. Skim any mold/yeast from the surface of the water, but don't worry if you can't get it all. If there's mold, be sure to rinse the bag & put back. Taste the pickles after about a week.
. Feel free to remove and eat the pickles as they continue to ferment, until you decide how sour you like them - longer fermentation will increase sourness. Continue to check occasionally.
. Eventually, after one to four weeks (depending on the temperature), the pickles will be fully sour. Continue to enjoy them, moving them to the fridge to slow down fermentation. I usually leave mine for roughly 2 weeks.

== THE KEYS TO SUCCESSFUL FERMENTS

* Keep everything underneath the brine - make sure nothing rises to, or floats on, the surface. Anything on the surface will go mouldy after a while.
* Leave several inches of head space at the top of the jar - i.e. several inches of clear brine, above the ferment & weights.
* You may get kahm yeast on the surface of the water. It looks like a thin white mostly flat layer/patches on the surface. It's harmless, but if you leave it too long it'll make things taste off - skim it off with a spoon or kitchen paper. Anything furry/hairy is mould, if you catch it early, skim it off and carry on. If it looks black/pink/angry or has taken over, remove it, try a pickle and see what you think, but maybe compost the lot to be on the safe side.
* Either don't fully seal the jar, or unscrew the lid every day or two - the ferment will produce some CO₂, possibly causing jars/lids to burst.
* If you find yourself doing a lot of fermenting in mason jars, these are excellent and reduce mould and increase ease & reliability quite a bit: https://www.amazon.co.uk/Easy-Fermenter-Wide-Mouth-Lid/dp/B01DJVVORE/[Easy Fermenter Wide Mouth Lid Kit]

== Mixed Vegetable Ferments

The process described above is not limited to cucumber pickles. Pretty much any vegetable you have in abundance, except for ripe tomatoes which get soft and lose their form, can be fermented in this way. Basically, anything crunchy at the start, will ferment well this way.

Good luck and let me know how you get on!
Dunc
