= Violence Against Land Defenders On Wet'suwet'en Territory

:tags: politics,canada,environment
:category: politics
:status: draft

Dear MLA,

As a constituent in your riding, I'm writing to express my disgust (but sadly not surprise) at the violence committed against land defenders on Wet'suwet'en territory. 

We are literally up to our necks in landslides and floods directly caused by climate change.  These people a fighting fossil fuel infrastructure - something that we should all be doing.

Yet, not only is the BCNDP violently repressing people trying to protect their land - and our climate - you are also giving billions of dollars of our money in subsidies to the fossil fuel industry!

Please fight for our future, not against it. Please stand up and say something.

Please speak out publicly to call off the RCMP, call for the release of land defenders, and halt all construction on CGL and all subsidies to the fossil fuel industry.

Your constituents are paying attention. 

Sincerely,

<Name Here>
<Postcode Here>