= You Should Write to Your UK MP about Corruption Now

:slug: you-should-write-to-your-uk-mp-about-corruption-now
:date: 2021-11-06 08:45:00-07:00
:tags: politics,uk
:category: politics
:meta_description: I've just emailed my UK MP to complain about government corruption & Owen Patterson. You should do the same.

I've just emailed my UK MP to https://www.bbc.com/news/explainers-59147044[complain about government corruption & Owen Patterson]. You should do the same. As always, we need as many people as possible to speak out. 

This is what I wrote, if anyone wants some ideas:

[quote]
____
<My Name> +
<My Address> +
<My Email Address>

Dear <MP Name>,

Like many others, I am angered - but not very surprised - by the latest revelations of government corruption, revealed by the corrupt behaviour of Owen Patterson.

I do have to admit to being slightly surprised that the government's reaction to this was naked collusion and a blatant attempt to water down the rules & standards!

The existing Committee on Standards needs to be strengthened, not weakened by the introduction of another Conservative-dominated committee overseeing its work.

The government needs to adopt the recommendations of numerous independent bodies - such as the anti-corruption watchdog the Committee on Standards in Public Life - that rules about MPs' behaviour should be tightened.

As a voter in your constituency, this issue is important to me - and the governments actions so far are not good enough!

Yours sincerely,

<Your Name>
____

This form makes it easy to email your MP about this issue: https://do.opendemocracy.net/MPstandards. It'll take 5 minutes - and it's better than _just_ being annoyed.

== Getting in Touch with your MP

Getting in touch with your MP generally is much easier than it used to be. You can use www.theyworkforyou.com to find your UK MP and see what they've been up to - as well as sending them a message.

* Does your MP represent you?: https://www.theyworkforyou.com/
* Write to your politicians, national or local, for free: https://www.writetothem.com/
